export const products = [
    {
        id: 1,
        name: "Увлажняющий мусс",
        skinType: "Для нормальной кожи",
        description: "Глубоко увлажняет кожу лица, оставляя её мягкой и гладкой.",
        image: "./src/assets/images/moisturizing-mousse.png",
        ingredients: [
            "активные натуральные комплексы",
            "витамины C, A, PP,B и E",
            "солнцезащитные компоненты",
        ],
        price: 2750,
        currency: "₽",
    },
    {
        id: 2,
        name: "Увлажняющая маска",
        skinType: "Для нормальной кожи",
        description: "Способствует удерживанию влаги в верхних слоях кожи.",
        image: "./src/assets/images/moisturizing-mask.png",
        ingredients: ["воски", "минералы", "масла"],
        price: 3500,
        currency: "₽",
    },
    {
        id: 3,
        name: "Гель для умывания",
        skinType: "Для нормальной кожи",
        description: "Интенсивно очищает, не повреждает защитный барьер кожи.",
        image: "./src/assets/images/cleansing-gel.png",
        ingredients: [
            "минералы",
            "витамины C, A, PP,B и E",
            "солнцезащитные компоненты",
        ],
        price: 1650,
        currency: "₽",
    },
    {
        id: 4,
        name: "Подарочный набор №1",
        skinType: "Для нормальной кожи",
        description: "Набор состоящий из увлажняющего крема и маски",
        image: "./src/assets/images/gift-set-1.png",
        ingredients: ["воски", "минералы", "масла"],
        price: 4750,
        currency: "₽",
    },
    {
        id: 5,
        name: "Подарочный набор №5",
        skinType: "Для нормальной кожи",
        description:
            "Весь набор средств Invisible symphony крем, маска, мусс и гель для умывания",
        image: "./src/assets/images/gift-set-5.png",
        ingredients: ["воски", "минералы", "масла"],
        price: 7520,
        currency: "₽",
    },
];
